import {
    image1,
    image2,
    image3,
    image4,
    image5,
    image6,
    image7,
    image8,
} from ".";

export default [
    {
        id: "1",
        name: "Herb-blended Pre-roll",
        image: image1,
        type: "Active Day",
        weight: "",
        pack: "",
        category: "Pre-Rolls",
        price: 35,
        stock: "New Arrival",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "2",
        name: "Herb-blended Pre-roll",
        image: image2,
        type: "Peaceful Day",
        weight: "",
        pack: "",
        category: "Pre-Rolls",
        price: 35,
        stock: "Out of Stock",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "3",
        name: "Strawberry Froasted Donut",
        image: image3,
        type: "",
        weight: "25mg",
        pack: "",
        category: "Bakery",
        price: 45,
        stock: "New Arrival",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "4",
        name: "Funfettin Cupcake",
        image: image8,
        type: "",
        weight: "25mg",
        pack: "",
        category: "Bakery",
        price: 45,
        stock: "Out of Stock",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "5",
        name: "Pecan Sticky Bun",
        image: image4,
        type: "",
        weight: "25mg",
        pack: "",
        category: "Bakery",
        price: 45,
        stock: "New Arrival",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "6",
        name: "Jelly Donut Holes",
        image: image5,
        type: "",
        weight: "100mg",
        pack: "4",
        category: "Bakery",
        price: 45,
        stock: "Out of Stock",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "7",
        name: "Chocolate Chip Muffin",
        image: image6,
        type: "",
        weight: "25mg",
        pack: "",
        category: "Bakery",
        price: 45,
        stock: "New Arrival",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
    {
        id: "8",
        name: "Chocolate Chip Cookies",
        image: image7,
        type: "",
        weight: "100mg",
        pack: "5",
        category: "Bakery",
        price: 45,
        stock: "Out of Stock",
        rating: 4,
        reviews: 13,
        orderNumber: "23566745",
        date: "Mar 2, 2022 | 2:00 PM",
        status: "Awaiting Pick-up",
    },
];
